name: Android CI

on:
  push:
    paths:
      - 'packages/android/**'
  pull_request:
    paths:
      - 'packages/android/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint-test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: packages/android/umbrel-app/*.gradle*

      - name: Run Lint
        run: gradle :app:lintDebug
        working-directory: packages/android/umbrel-app

      - name: Run Unit Tests
        run: gradle :app:testDebugUnitTest
        working-directory: packages/android/umbrel-app
